### ISSUE TITLE
error in daylight and unrooted layouts

### ISSUE THREAD

**Issue by LordArnav** [YuLab-SMU/ggtree#287]
hi im new to R, i have recently installed ggtree. im getting the following error when trying to use "daylight" and "unrooted" layouts:
"Error in UseMethod("child") : 
  no applicable method for 'child' applied to an object of class "data.frame"
the other layouts work just fine.
any suggestions?
i have copied the example from the ggtree book:
> library(ggtree)
> set.seed(2017-02-16)
> tree <- rtree(50)
> ggtree(tree)
> ggtree(tree, layout="slanted") 
> ggtree(tree, layout="circular")
> ggtree(tree, layout="fan", open.angle=120)
> ggtree(tree, layout="equal_angle")
> ggtree(tree, layout="daylight")
Error in UseMethod("child") : 
  no applicable method for 'child' applied to an object of class "data.frame"
> ggtree(tree, branch.length='none')
> ggtree(tree, branch.length='none', layout='circular')
> ggtree(tree, layout="daylight", branch.length = 'none')
Error in UseMethod("child") : 
  no applicable method for 'child' applied to an object of class "data.frame"

**Comment by brj1** [comment]
@GuangchuangYu the problem here is that ` rotateTreePoints.df` is changing the inputted `tibble` into a `data.frame`.

**Comment by GuangchuangYu** [comment]
Can you reproduce this error using latest version? I can't reproduce it.

**Comment by LordArnav** [comment]
hi, thank you very much for helping, anyway ggtree is wonderful. Yes, i can reproduce this error, i get it every time i try unrooted and daylight layouts. im using ggtree 2.0.2 is it the latest?  
this is the R session if it helps.. what further can i try to do?

> library(ggtree)
> set.seed(2017-02-16)
> tree <- rtree(50)
> ggtree(tree, layout="daylight")
Error in UseMethod("child") : 
  no applicable method for 'child' applied to an object of class "data.frame"
> ggtree(tree, layout="unrooted")
"daylight" method was used as default layout for unrooted tree.
Error in UseMethod("child") : 
  no applicable method for 'child' applied to an object of class "data.frame"
sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggtree_2.0.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4          rstudioapi_0.11     magrittr_1.5        tidyselect_1.0.0    munsell_0.5.0      
 [6] colorspace_1.4-1    ape_5.3             lattice_0.20-38     R6_2.4.1            rlang_0.4.5        
[11] dplyr_0.8.5         tools_3.6.3         parallel_3.6.3      grid_3.6.3          nlme_3.1-144       
[16] gtable_0.3.0        lazyeval_0.2.2      assertthat_0.2.1    tibble_2.1.3        lifecycle_0.2.0    
[21] crayon_1.3.4        treeio_1.10.0       tidyr_1.0.2         BiocManager_1.30.10 purrr_0.3.3        
[26] ggplot2_3.3.0       vctrs_0.2.4         tidytree_0.3.3      glue_1.3.2          compiler_3.6.3     
[31] pillar_1.4.3        rvcheck_0.1.8       scales_1.1.0        jsonlite_1.6.1      pkgconfig_2.0.3

**Comment by deprekate** [comment]
I have potentially the same issue with both daylight and unrooted, but with a different error message:
```
> library(ggtree)
> set.seed(2017-02-16)
> tree <- rtree(50)
> ggtree(tree)
Warning message:
`data_frame()` is deprecated as of tibble 1.1.0.
Please use `tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
> ggtree(tree, layout="slanted")
> ggtree(tree, layout="circular")
> ggtree(tree, layout="fan", open.angle=120)
> ggtree(tree, layout="equal_angle")
Error: Assigned data `2` must be compatible with existing data.
ℹ Error occurred for column `end`.
✖ Lossy cast from `value` <double> to `x` <logical>.
* Locations: 1.
Run `rlang::last_error()` to see where the error occurred.
> ggtree(tree, layout="daylight")
Error: Assigned data `2` must be compatible with existing data.
ℹ Error occurred for column `end`.
✖ Lossy cast from `value` <double> to `x` <logical>.
* Locations: 1.
Run `rlang::last_error()` to see where the error occurred.
```
```
> rlang::last_error()
<error/tibble_error_assign_incompatible_type>
Assigned data `2` must be compatible with existing data.
ℹ Error occurred for column `end`.
✖ Lossy cast from `value` <double> to `x` <logical>.
* Locations: 1.
Backtrace:
  1. ggtree::ggtree(tree, layout = "daylight")
  3. ggplot2:::ggplot.default(...)
  5. ggtree:::fortify.phylo(data, ...)
  6. ggtree:::layout.unrooted(...)
  7. ggtree:::layoutDaylight(model, branch.length, MAX_COUNT)
  8. ggtree:::layoutEqualAngle(model, branch.length)
 10. tibble:::`[<-.tbl_df`(`*tmp*`, root, "end", value = 2)
 11. tibble:::tbl_subassign(x, i, j, value, i_arg, j_arg, substitute(value))
 12. tibble:::tbl_subassign_row(xj, i, value, value_arg)
 13. base::tryCatch(...)
 14. base:::tryCatchList(expr, classes, parentenv, handlers)
 15. base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 16. value[[3L]](cond)
Run `rlang::last_trace()` to see the full context.
```
```
> rlang::last_trace()
<error/tibble_error_assign_incompatible_type>
Assigned data `2` must be compatible with existing data.
ℹ Error occurred for column `end`.
✖ Lossy cast from `value` <double> to `x` <logical>.
* Locations: 1.
Backtrace:
     █
  1. └─ggtree::ggtree(tree, layout = "daylight")
  2.   ├─ggplot2::ggplot(...)
  3.   └─ggplot2:::ggplot.default(...)
  4.     ├─ggplot2::fortify(data, ...)
  5.     └─ggtree:::fortify.phylo(data, ...)
  6.       └─ggtree:::layout.unrooted(...)
  7.         └─ggtree:::layoutDaylight(model, branch.length, MAX_COUNT)
  8.           └─ggtree:::layoutEqualAngle(model, branch.length)
  9.             ├─base::`[<-`(`*tmp*`, root, "end", value = 2)
 10.             └─tibble:::`[<-.tbl_df`(`*tmp*`, root, "end", value = 2)
 11.               └─tibble:::tbl_subassign(x, i, j, value, i_arg, j_arg, substitute(value))
 12.                 └─tibble:::tbl_subassign_row(xj, i, value, value_arg)
 13.                   └─base::tryCatch(...)
 14.                     └─base:::tryCatchList(expr, classes, parentenv, handlers)
 15.                       └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 16.                         └─value[[3L]](cond)
> 
```

and my environment info
```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggtree_2.0.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6        magrittr_1.5        tidyselect_1.0.0    munsell_0.5.0       colorspace_1.4-1    ape_5.3             lattice_0.20-41     R6_2.4.1           
 [9] rlang_0.4.5         fansi_0.4.1         dplyr_0.8.5         tools_3.6.3         parallel_3.6.3      grid_3.6.3          nlme_3.1-145        gtable_0.3.0       
[17] cli_2.0.2           ellipsis_0.3.0      lazyeval_0.2.2      assertthat_0.2.1    tibble_3.0.0        lifecycle_0.2.0     crayon_1.3.4        treeio_1.10.0      
[25] tidyr_1.0.2         BiocManager_1.30.10 purrr_0.3.3         ggplot2_3.3.0       vctrs_0.2.4         tidytree_0.3.3      glue_1.4.0          compiler_3.6.3     
[33] pillar_1.4.3        rvcheck_0.1.8       scales_1.1.0        jsonlite_1.6.1      pkgconfig_2.0.3    

> packageVersion("ggtree")
[1] ‘2.0.2’
```

**Comment by LordArnav** [comment]
Hi,  I got the same issue after updating tibble to version 3.0.0 , now I'm using version 2.1.3

**Comment by GuangchuangYu** [comment]
the issue posted by @deprekate is caused by the new version of tibble (3.0.0) and it has been fixed yesterday in ggtree 2.0.3 which will be available soon on bioconductor.

**Comment by LordArnav** [comment]
hi, thanks for the update, i have updated to version 2.0.3 but i still get this error when trying to use unrooted and daylight layouts:
Error in UseMethod("child") : 
  no applicable method for 'child' applied to an object of class "data.frame"
is there anything i can try to fix this? 
> set.seed(2017-02-16)
>  tree <- rtree(50)
>  ggtree(tree, layout = "daylight")
Error in UseMethod("child") : 
  no applicable method for 'child' applied to an object of class "data.frame"
>  ggtree(tree, layout = "unrooted")
"daylight" method was used as default layout for unrooted tree.
Error in UseMethod("child") : 
  no applicable method for 'child' applied to an object of class "data.frame"
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] ggtree_2.0.3

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6        pillar_1.4.3       
 [3] compiler_3.6.3      BiocManager_1.30.10
 [5] tools_3.6.3         jsonlite_1.6.1     
 [7] tidytree_0.3.3      lifecycle_0.2.0    
 [9] tibble_3.0.0        gtable_0.3.0       
[11] nlme_3.1-144        lattice_0.20-38    
[13] pkgconfig_2.0.3     rlang_0.4.5        
[15] cli_2.0.2           rstudioapi_0.11    
[17] rvcheck_0.1.8       parallel_3.6.3     
[19] treeio_1.10.0       dplyr_0.8.5        
[21] vctrs_0.2.4         ade4_1.7-15        
[23] grid_3.6.3          tidyselect_1.0.0   
[25] glue_1.4.0          R6_2.4.1           
[27] fansi_0.4.1         ggplot2_3.3.0      
[29] purrr_0.3.3         tidyr_1.0.2        
[31] seqinr_3.6-1        magrittr_1.5       
[33] scales_1.1.0        ellipsis_0.3.0     
[35] MASS_7.3-51.5       assertthat_0.2.1   
[37] ape_5.3             colorspace_1.4-1   
[39] lazyeval_0.2.2      munsell_0.5.0      
[41] crayon_1.3.4       
>

**Comment by GuangchuangYu** [comment]
traceback() output?

**Comment by LordArnav** [comment]
hi, i hope this helps. thanks allot !
> ggtree(tree, layout = "daylight")
Error in UseMethod("child") : 
  no applicable method for 'child' applied to an object of class "data.frame"
> traceback()
10: tidytree::child(df, node)
9: getSubtreeUnrooted.df(df, node_id)
8: applyLayoutDaylight(tree_df, currentNode_id)
7: layoutDaylight(model, branch.length, MAX_COUNT)
6: layout.unrooted(model, layout.method = layout, branch.length = branch.length, 
       ...)
5: fortify.phylo(data, ...)
4: fortify(data, ...)
3: ggplot.default(tr, mapping = mapping, layout = layout, mrsd = mrsd, 
       as.Date = as.Date, yscale = yscale, yscale_mapping = yscale_mapping, 
       ladderize = ladderize, right = right, branch.length = branch.length, 
       root.position = root.position, ...)
2: ggplot(tr, mapping = mapping, layout = layout, mrsd = mrsd, as.Date = as.Date, 
       yscale = yscale, yscale_mapping = yscale_mapping, ladderize = ladderize, 
       right = right, branch.length = branch.length, root.position = root.position, 
       ...)
1: ggtree(tree, layout = "daylight")

**Comment by GuangchuangYu** [comment]
@LordArnav Can you try 
1. `remotes::install_github("YuLab-SMU/ggtree")` to upgrade ggtree
2. restart R
3. test with your code

**Comment by LordArnav** [comment]
i uprgraded and this is the error now:
> library(ggtree)
> set.seed(2017-02-16)
> tree <- rtree(50)
> ggtree(tree, layout = "daylight")
Error in UseMethod("parent") : 
  no applicable method for 'parent' applied to an object of class "data.frame"
> traceback()
10: parent(df, node)
9: getSubtreeUnrooted.df(df, node_id)
8: applyLayoutDaylight(tree_df, currentNode_id)
7: layoutDaylight(model, branch.length, MAX_COUNT)
6: layout.unrooted(model, layout.method = layout, branch.length = branch.length, 
       ...)
5: fortify.phylo(data, ...)
4: fortify(data, ...)
3: ggplot.default(tr, mapping = mapping, layout = layout, mrsd = mrsd, 
       as.Date = as.Date, yscale = yscale, yscale_mapping = yscale_mapping, 
       ladderize = ladderize, right = right, branch.length = branch.length, 
       root.position = root.position, ...)
2: ggplot(tr, mapping = mapping, layout = layout, mrsd = mrsd, as.Date = as.Date, 
       yscale = yscale, yscale_mapping = yscale_mapping, ladderize = ladderize, 
       right = right, branch.length = branch.length, root.position = root.position, 
       ...)
1: ggtree(tree, layout = "daylight")

**Comment by GuangchuangYu** [comment]
pls try the three steps again.

**Comment by LordArnav** [comment]
Eurika !! it works now, thank you very much for your time! i really appreciate it,
